#-----------------------------Aula 3-----------------------------------------
frase = "Curso em vídeo Python"
espaco = '   Aprendendo Python  '
print(frase[:5])
print(frase[15:])
print(frase[9::3])

len(frase)
frase.count('o',0,13)
frase.find('deo')
frase.find('Android')
frase.replace('Python', 'Android')
frase.upper()
frase.lower()
frase.capitalize()
frase.title()
espaco.strip()
frase.split()
'-'.join(frase)

print(len(frase))
print(frase.count("o"))
print(frase.find('deo'))
print(frase.find('Android'))
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(espaco.strip())
print(espaco.rstrip())
print(espaco.lstrip())
print(frase.split())
print('-'.join(frase))
print('Curso' in frase)