nt = int(input('Qual número você quer descobrir a tabuada? '))
print('-' * 15)
print(f'{1:2}x{nt}={nt*1}')
print(f'{2:2}x{nt}={nt*2}')
print(f'{3:2}x{nt}={nt*3}')
print(f'{4:2}x{nt}={nt*4}')
print(f'{5:2}x{nt}={nt*5}')
print(f'{6:2}x{nt}={nt*6}')
print(f'{7:2}x{nt}={nt*7}')
print(f'{8:2}x{nt}={nt*8}')
print(f'{9:2}x{nt}={nt*9}')
print(f'{10}x{nt}={nt*10}')
print('-' * 15)